### ISSUE TITLE
승인서버 999 error 코드

### ISSUE THREAD

**Issue by seungheoni** [ued123/modeling#168]
modeling 어플리케이션에서 oauth2 client를 적용하고 **리다이렉트 url을 설정하고 authorization_code**를 받아보려고 했는데, 승인 서버에서 로그인 이후 redirect_url로 이동전에 status=999가 떨어지는데 왜그럴까요?..
아래는 modeling 설정
```yml
security:
...
          sangho: # registrationId
            provider: sangho
            client-id: public-client
            client-secret: e25vb3B9cHVibGljLXNlY3JldHRlbG5ldCAK
            clientAuthenticationMethod: client_secret_post
            authorizationGrantType: authorization_code
            redirectUri: http://127.0.0.1:8080/login/oauth2/code/sangho
            scope:
              - openid
            clientName: 8d75205d-aab5-4e02-aab3-65ba4663d224
        provider:
          sangho:
            authorizationUri: http://localhost:9090/oauth2/v1/authorize
            tokenUri: http://localhost:9090/oauth2/v1/token
            userInfoUri: http://localhost:9090/connect/v1/userinfo
            jwkSetUri: http://localhost:9090/oauth2/v1/jwks
            userNameAttribute: sub
```

1. localhost:9090 로그인 후 redirect_url (http://127.0.0.1:8080/login/oauth2/code/sangho)로 이동 전에 error 페이지
<img width="745" alt="image" src="https://user-images.githubusercontent.com/32861341/224851370-6588c52e-5ff9-4ac2-ad52-c68ba21944e2.png">
